services:
  nginx_proxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxymanager
    restart: unless-stopped
    ports:
      - '443:443' # HTTPS Only
      - '8123:81' # Dashboard NginxProxyManager
    environment:
      DB_MYSQL_HOST: "nginx_database"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm" # Please Change Default User
      DB_MYSQL_PASSWORD: "npm" # Please Change Default Password
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - nginx_database
    networks:
      - nginx_network
      - nginx_internal

  nginx_database:
    image: 'mariadb:latest'
    container_name: nginx_database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm' # Please Change Root Password
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm' # Please Change Default User
      MYSQL_PASSWORD: 'npm' # Please Change Default Password
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - nginx_internal

networks:
  nginx_network:
  nginx_internal:
