services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    ports:
      - '19443:9443' # Dashboard Portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - portainer_network

volumes:
  portainer_data:

networks:
  portainer_network:
