services:
  portainer_app:
    image: portainer/portainer-ce:lts
    container_name: portainer_app
    restart: unless-stopped
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - portainer_network

volumes:
  portainer_data:
    name: portainer_data

networks:
  portainer_network:
